// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using AbpProject;

// ReSharper disable once CheckNamespace
namespace AbpProject.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPersonService), typeof(PersonClientProxy))]
public partial class PersonClientProxy : ClientProxyBase<IPersonService>, IPersonService
{
    public virtual async Task<List<Person>> GetAsync(string name)
    {
        return await RequestAsync<string>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<Person> PostAsync(Person mode)
    {
        return await RequestAsync<Person>(nameof(PostAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Person), mode }
        });
    }
}
